name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Monkey C
      run: |
        wget https://developer.garmin.com/downloads/connect-iq/sdks/connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee.zip
        unzip connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee.zip
        echo "sdk.location=$(pwd)/connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee" > local.properties
        ./connectiq-sdk-lin-4.1.4-2022-06-07-f86da2dee/bin/monkeyc -y developer_key.der -f monkey.jungle -o output.prg
